void abft_dpotf2(const char uplo, int n, double * A, int lda, int * info, 
			  	 int nb, 
			     double * colchk, int ld_colchk, 
			     double * rowchk, int ld_rowchk, 
			     double * chk_v, int ld_chk_v, 
			     bool FT, bool DEBUG, bool CHECK_BEFORE, bool CHECK_AFTER);

void abft_dtrsm_work(
    magma_side_t side, magma_uplo_t uplo, magma_trans_t transA, magma_diag_t diag,
    int m, int n,
    double alpha,
    double * dA, int ldda,
    double *       dB, int lddb,
    double *       dX, int lddx,
    int flag,
    double * d_dinvA, int dinvA_length,
    int nb,
    double * dA_colchk,    int ldda_colchk,
    double * dA_rowchk,    int ldda_rowchk,
    double * dA_colchk_r,  int ldda_colchk_r,
    double * dA_rowchk_r,  int ldda_rowchk_r,
    double * dB_colchk,    int lddb_colchk,
    double * dB_rowchk,    int lddb_rowchk,
    double * dB_colchk_r,  int lddb_colchk_r,
    double * dB_rowchk_r,  int lddb_rowchk_r,
    double * chk_v,        int ld_chk_v, 
    bool FT, bool DEBUG, bool CHECK_BEFORE, bool CHECK_AFTER,
    magma_queue_t stream1, magma_queue_t stream2);

void abft_dsyrk(magma_uplo_t uplo, magma_trans_t trans,
                 int n, int k, 
                 double alpha,
                 double * dA, int ldda,
                 double beta,
                 double * dC, int lddc,
                 int nb,
                 double * dA_colchk,    int ldda_colchk,
                 double * dA_rowchk,    int ldda_rowchk,
                 double * dA_colchk_r,  int ldda_colchk_r,
                 double * dA_rowchk_r,  int ldda_rowchk_r,
                 double * dC_colchk,    int lddc_colchk,
                 double * dC_rowchk,    int lddc_rowchk,
                 double * dC_colchk_r,  int lddc_colchk_r,
                 double * dC_rowchk_r,  int lddc_rowchk_r,
                 double * chk_v,        int ld_chk_v, 
                 bool FT, bool DEBUG, bool CHECK_BEFORE, bool CHECK_AFTER,
                 magma_queue_t stream1, magma_queue_t stream2);

void dgemmFT( magma_trans_t transA, magma_trans_t transB,
              int m, int n, int k, 
              double alpha, 
              double * dA, int ldda,
              double * dB, int lddb, 
              double beta, 
              double * dC, int lddc,
              int nb,
              double * dA_colchk,   int ldda_colchk,
              double * dA_rowchk,   int ldda_rowchk,
              double * dA_colchk_r, int ldda_colchk_r,
              double * dA_rowchk_r, int ldda_rowchk_r,
              double * dB_colchk,   int lddb_colchk,
              double * dB_rowchk,   int lddb_rowchk,
              double * dB_colchk_r, int lddb_colchk_r,
              double * dB_rowchk_r, int lddb_rowchk_r,
              double * dC_colchk,   int lddc_colchk,
              double * dC_rowchk,   int lddc_rowchk,
              double * dC_colchk_r, int lddc_colchk_r,
              double * dC_rowchk_r, int lddc_rowchk_r,
              double * chk_v, int ld_chk_v, 
              bool FT, bool DEBUG, bool CHECK_BEFORE, bool CHECK_AFTER,
              magma_queue_t stream1, magma_queue_t stream2);